/**
* @author SalesforceXyTools
* @homepage http://salesforcexytools.com
*/
@isTest
private class AccountHandlerTest {

    /**
     * This is a test method for onBeforeUpdate
     */
    static testMethod void test_onBeforeUpdate() {

        // PageReference pageRef = Page.undefined;
        // Test.setCurrentPage(pageRef);
        // pageRef.getParameters().put('param1', 'param1');

        Test.startTest();

        // List oldObjs;
        // Map oldObjMap;
        // List newObjs;
        // Map newObjMap;
        // AccountHandler obj = new AccountHandler();
        // obj.onBeforeUpdate(oldObjs , oldObjMap , newObjs , newObjMap);

        Test.stopTest();

        // Check
        // System.assert(ApexPages.hasMessages());
        // for(ApexPages.Message msg : ApexPages.getMessages()) {
        //     System.assertEquals('Upload file is NULL', msg.getSummary());
        //     System.assertEquals(ApexPages.Severity.ERROR, msg.getSeverity());
        // }
    }


    /**
     * This is a test method for onAfterUpdate
     */
    static testMethod void test_onAfterUpdate() {

        // PageReference pageRef = Page.undefined;
        // Test.setCurrentPage(pageRef);
        // pageRef.getParameters().put('param1', 'param1');

        Test.startTest();

        // List oldObjs;
        // Map oldObjMap;
        // List newObjs;
        // Map newObjMap;
        // AccountHandler obj = new AccountHandler();
        // obj.onAfterUpdate(oldObjs , oldObjMap , newObjs , newObjMap);

        Test.stopTest();

        // Check
        // System.assert(ApexPages.hasMessages());
        // for(ApexPages.Message msg : ApexPages.getMessages()) {
        //     System.assertEquals('Upload file is NULL', msg.getSummary());
        //     System.assertEquals(ApexPages.Severity.ERROR, msg.getSeverity());
        // }
    }

}